import json
import subprocess
import sys
from pathlib import Path

from weaver.analyzer import analyze_html
from weaver.codegen import generate_scraper
from weaver.models import DetailSpec, FieldSpec, ScrapeSpec


def test_generated_scraper_compiles_and_is_polite() -> None:
    html = (Path(__file__).parent / "fixtures" / "shop.html").read_text()
    spec = analyze_html(html, "https://shop.example/").spec
    source = generate_scraper(spec)
    compile(source, "scraper.py", "exec")
    assert "robots_txt_obey = not ROBOTS_BYPASS" in source
    assert 'ROBOTS_POLICY = SPEC.get("robots_policy", "fail_closed")' in source
    assert "concurrent_requests_per_domain = 1" in source
    assert "preflight_robots" in source
    assert "node.get_all_text()" in source
    assert "follow_redirects=False" in source
    assert "MAX_PAGES" in source
    assert "_next_page_url" in source
    assert "_weaver_seen_rows" in source
    assert "concurrent_requests = 1" in source
    assert "--report-url" in source
    assert "_report_failure" in source
    assert "_validate_runtime_contract" in source
    assert "OpenAI" not in source


def test_generated_scraper_embeds_client_authorized_robots_bypass(monkeypatch, capsys) -> None:
    fixture = Path(__file__).parent / "fixtures" / "shop.html"
    spec = analyze_html(fixture.read_text(), "https://shop.example/").spec.model_copy(
        update={"robots_policy": "client_authorized_bypass"}
    )

    source = generate_scraper(spec)

    compile(source, "bypass_scraper.py", "exec")
    assert '"robots_policy": "client_authorized_bypass"' in source
    assert "ROBOTS_BYPASS = ROBOTS_POLICY == \"client_authorized_bypass\"" in source
    assert "CLIENT-AUTHORIZED BYPASS" in source
    assert "robots_txt_obey = not ROBOTS_BYPASS" in source
    assert "or not _robots_allows(request.url)" in source
    assert "if not _robots_allows(next_url):" in source

    def unexpected_robots_fetch(*_args, **_kwargs):
        raise AssertionError("generated bypass runtime must not request robots.txt")

    monkeypatch.setattr("urllib.request.build_opener", unexpected_robots_fetch)
    namespace = {"__name__": "weaver_generated_test"}
    exec(source, namespace)
    assert namespace["preflight_robots"]("https://shop.example/") == 1.0
    assert namespace["GeneratedSpider"].robots_txt_obey is False
    assert namespace["_robots_allows"]("https://shop.example/next") is True
    assert "CLIENT-AUTHORIZED BYPASS" in capsys.readouterr().out


def test_generated_scraper_executes_against_fixture(tmp_path: Path) -> None:
    fixture = Path(__file__).parent / "fixtures" / "shop.html"
    spec = analyze_html(fixture.read_text(), "https://shop.example/").spec
    scraper = tmp_path / "scraper.py"
    output = tmp_path / "rows.json"
    scraper.write_text(generate_scraper(spec), encoding="utf-8")
    subprocess.run(
        [sys.executable, str(scraper), "--fixture", str(fixture), "--output", str(output)],
        check=True,
        capture_output=True,
        text=True,
        timeout=20,
    )
    rows = json.loads(output.read_text())
    assert len(rows) == 3
    assert rows[0]["title"] == "Trail Mug"


def test_service_and_generated_runtime_normalize_dom_whitespace_identically(tmp_path: Path) -> None:
    fixture = tmp_path / "jobs.html"
    fixture.write_text(
        '<main><article class="job"><h2>Senior Program Manager - <span> Gen- </span> 1</h2><a href="/1">Apply</a></article>'
        '<article class="job"><h2>Flight Engineer - <span> Gen- </span> 2</h2><a href="/2">Apply</a></article></main>',
        encoding="utf-8",
    )
    analysis = analyze_html(
        fixture.read_text(),
        "https://company.example/careers",
        "jobs",
        prefer_jsonld=False,
    )
    scraper = tmp_path / "jobs.py"
    output = tmp_path / "jobs.json"
    scraper.write_text(generate_scraper(analysis.spec), encoding="utf-8")

    subprocess.run(
        [sys.executable, str(scraper), "--fixture", str(fixture), "--output", str(output)],
        check=True,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert json.loads(output.read_text()) == analysis.rows


def test_rendered_spec_configures_browser_session() -> None:
    fixture = Path(__file__).parent / "fixtures" / "shop.html"
    spec = analyze_html(fixture.read_text(), "https://shop.example/").spec.model_copy(
        update={"render_mode": "browser"}
    )
    source = generate_scraper(spec)
    assert 'SPEC.get("render_mode") == "browser"' in source
    assert "AsyncStealthySession" in source
    assert '"solve_cloudflare": True' in source
    assert '"timeout": 90_000' in source
    assert '"retries": 3' in source
    compile(source, "browser_scraper.py", "exec")


def test_generated_jsonld_filters_unrelated_typed_nodes(tmp_path: Path) -> None:
    fixture = tmp_path / "mixed.html"
    fixture.write_text(
        '<script type="application/ld+json">'
        '{"@graph":[{"@type":"Organization","name":"Wrong Corp"},'
        '{"@type":"Product","name":"Right Product","offers":{"price":"12.00"}}]}'
        "</script>",
        encoding="utf-8",
    )
    spec = analyze_html(fixture.read_text(), "https://shop.example/", "ecommerce").spec
    scraper = tmp_path / "jsonld_scraper.py"
    output = tmp_path / "jsonld_rows.json"
    scraper.write_text(generate_scraper(spec), encoding="utf-8")
    subprocess.run(
        [sys.executable, str(scraper), "--fixture", str(fixture), "--output", str(output)],
        check=True,
        capture_output=True,
        text=True,
        timeout=20,
    )
    rows = json.loads(output.read_text())
    assert [row["title"] for row in rows] == ["Right Product"]


def test_generated_scraper_honors_limit_and_skips_images(tmp_path: Path) -> None:
    fixture = Path(__file__).parent / "fixtures" / "shop.html"
    spec = analyze_html(fixture.read_text(), "https://shop.example/").spec.model_copy(
        update={"max_items": 2, "image_mode": "skip"}
    )
    scraper = tmp_path / "limited.py"
    output = tmp_path / "limited.json"
    scraper.write_text(generate_scraper(spec), encoding="utf-8")
    subprocess.run(
        [sys.executable, str(scraper), "--fixture", str(fixture), "--output", str(output)],
        check=True,
        capture_output=True,
        text=True,
        timeout=20,
    )
    rows = json.loads(output.read_text())
    assert len(rows) == 2
    assert all("image" not in row for row in rows)


def test_generated_scraper_enforces_collection_and_requested_field_contract(tmp_path: Path) -> None:
    fixture = tmp_path / "wrapper.html"
    fixture.write_text("<section><h2>Find open roles</h2></section>", encoding="utf-8")
    spec = ScrapeSpec(
        source_url="https://company.example/careers",
        category="jobs",
        strategy="css",
        container="section",
        min_rows=2,
        requested_field_names=["apply_url"],
        fields=[FieldSpec(name="title", selector="h2")],
    )
    scraper = tmp_path / "contract.py"
    output = tmp_path / "rows.json"
    scraper.write_text(generate_scraper(spec), encoding="utf-8")

    process = subprocess.run(
        [sys.executable, str(scraper), "--fixture", str(fixture), "--output", str(output)],
        check=False,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert process.returncode != 0
    assert "expected at least 2 records" in process.stderr


def test_generated_scraper_replays_multiple_pages_and_deduplicates(tmp_path: Path) -> None:
    page_one = tmp_path / "page-1.html"
    page_two = tmp_path / "page-2.html"
    page_one.write_text(
        '<section><article class="item"><h2>Alpha record</h2><a href="/a">Open</a></article>'
        '<article class="item"><h2>Beta record</h2><a href="/b">Open</a></article></section>',
        encoding="utf-8",
    )
    page_two.write_text(
        '<section><article class="item"><h2>Beta record</h2><a href="/b">Open</a></article>'
        '<article class="item"><h2>Gamma record</h2><a href="/g">Open</a></article></section>',
        encoding="utf-8",
    )
    spec = analyze_html(page_one.read_text(), "https://shop.example/list?page=1", prefer_jsonld=False).spec.model_copy(
        update={"max_pages": 10, "max_items": 20, "pagination_mode": "next_link", "next_page_selector": "a.next"}
    )
    scraper = tmp_path / "multi.py"
    output = tmp_path / "rows.json"
    manifest = tmp_path / "fixtures.json"
    scraper.write_text(generate_scraper(spec), encoding="utf-8")
    manifest.write_text(
        json.dumps(
            [
                {"path": str(page_one), "url": "https://shop.example/list?page=1"},
                {"path": str(page_two), "url": "https://shop.example/list?page=2"},
            ]
        ),
        encoding="utf-8",
    )
    process = subprocess.run(
        [sys.executable, str(scraper), "--fixture-manifest", str(manifest), "--output", str(output)],
        check=True,
        capture_output=True,
        text=True,
        timeout=20,
    )
    rows = json.loads(output.read_text())
    assert [row["title"] for row in rows] == ["Alpha record", "Beta record", "Gamma record"]
    assert "fixture page 2: 1 new rows" in process.stdout


def test_generated_scraper_replays_same_origin_article_details(tmp_path: Path) -> None:
    listing = tmp_path / "news.html"
    detail_one = tmp_path / "story-1.html"
    detail_two = tmp_path / "story-2.html"
    listing.write_text(
        '<article class="card"><a href="/story/1"><h2>First story</h2></a></article>'
        '<article class="card"><a href="/story/2"><h2>Second story</h2></a></article>',
        encoding="utf-8",
    )
    detail_one.write_text("<article><p>Complete first article body.</p><p>More first reporting.</p></article>", encoding="utf-8")
    detail_two.write_text("<article><p>Complete second article body.</p><p>More second reporting.</p></article>", encoding="utf-8")
    spec = ScrapeSpec(
        source_url="https://news.example/latest",
        category="news",
        strategy="css",
        container="article.card",
        fields=[
            FieldSpec(name="headline", selector="h2"),
            FieldSpec(name="url", selector="a", type="url", attribute="href"),
        ],
        detail=DetailSpec(
            url_field="url",
            fields=[FieldSpec(name="article_body", selector="article", required=True)],
        ),
    )
    scraper = tmp_path / "news_scraper.py"
    output = tmp_path / "news_rows.json"
    manifest = tmp_path / "news_fixtures.json"
    scraper.write_text(generate_scraper(spec), encoding="utf-8")
    manifest.write_text(
        json.dumps(
            {
                "pages": [{"path": str(listing), "url": "https://news.example/latest"}],
                "details": [
                    {"path": str(detail_one), "url": "https://news.example/story/1/"},
                    {"path": str(detail_two), "url": "https://news.example/story/2/"},
                ],
            }
        ),
        encoding="utf-8",
    )

    subprocess.run(
        [sys.executable, str(scraper), "--fixture-manifest", str(manifest), "--output", str(output)],
        check=True,
        capture_output=True,
        text=True,
        timeout=20,
    )
    rows = json.loads(output.read_text())
    assert [row["headline"] for row in rows] == ["First story", "Second story"]
    assert "Complete first article body" in rows[0]["article_body"]
    assert "Complete second article body" in rows[1]["article_body"]
