from __future__ import annotations

import json
from urllib.parse import urlsplit

import yaml

from .models import ScrapeSpec


def spec_yaml(spec: ScrapeSpec) -> str:
    payload = spec.model_dump(exclude_none=True)
    return yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)


def generate_scraper(spec: ScrapeSpec) -> str:
    """Render deterministic Python. The model never writes executable code."""
    hostname = urlsplit(spec.source_url).hostname or ""
    encoded_spec = repr(json.dumps(spec.model_dump(exclude_none=True), ensure_ascii=False))
    return f'''#!/usr/bin/env python3
"""Generated by Weaver.

AI was used only while designing the extraction spec. This runtime is deterministic.
Scrapling is a BSD-3-Clause dependency. Keep its license when redistributing it.
"""
from __future__ import annotations

import argparse
import asyncio
import ipaddress
import json
import os
import re
import socket
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urljoin, urlsplit, urlunsplit

from scrapling import Selector
from scrapling.fetchers import AsyncStealthySession, FetcherSession
from scrapling.spiders import Request, Response, SessionManager, Spider
from protego import Protego


SPEC = json.loads({encoded_spec})
USER_AGENT = "WeaverBot/0.1 (+respectful generated scraper)"
ALLOWED_HOST = {hostname!r}
ALLOWED_NETLOC = urlsplit(SPEC["source_url"]).netloc
_ROBOTS_PARSER: Protego | None = None
_BROWSER_DELAY = 1.0
_PUBLIC_HOST_CACHE: dict[str, bool] = {{}}
ROBOTS_POLICY = SPEC.get("robots_policy", "fail_closed")
ROBOTS_BYPASS = ROBOTS_POLICY == "client_authorized_bypass"
MAX_ITEMS = int(SPEC.get("max_items", 100))
MAX_PAGES = int(SPEC.get("max_pages", 25))
MIN_ROWS = int(SPEC.get("min_rows", 1))
PRIORITIZED_FIELDS = [str(name) for name in SPEC.get("requested_field_names", []) if name]
NEXT_SELECTOR = SPEC.get("next_page_selector")
ACTIVE_FIELDS = [
    field for field in SPEC["fields"]
    if SPEC.get("image_mode") != "skip" or field.get("type") != "image"
]
DETAIL = SPEC.get("detail")
ACTIVE_DETAIL_FIELDS = [
    field for field in (DETAIL or {{}}).get("fields", [])
    if SPEC.get("image_mode") != "skip" or field.get("type") != "image"
]


def _robots_url(url: str) -> str:
    parts = urlsplit(url)
    return urlunsplit((parts.scheme, parts.netloc, "/robots.txt", "", ""))


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, request, file_pointer, code, message, headers, new_url):
        return None


def preflight_robots(url: str) -> float:
    """Fail closed if robots rules cannot be evaluated."""
    global _ROBOTS_PARSER, _BROWSER_DELAY
    if ROBOTS_BYPASS:
        print("[Weaver] robots.txt: CLIENT-AUTHORIZED BYPASS — not fetched or enforced", flush=True)
        return _BROWSER_DELAY
    robots_url = _robots_url(url)
    opener = urllib.request.build_opener(_NoRedirect)
    lines: list[str] | None = None
    for redirect_count in range(5):
        request = urllib.request.Request(robots_url, headers={{"User-Agent": USER_AGENT}})
        try:
            with opener.open(request, timeout=15) as response:
                lines = response.read(1_000_000).decode("utf-8", "replace").splitlines()
                break
        except urllib.error.HTTPError as exc:
            if exc.code in {{404, 410}}:
                lines = []
                break
            if exc.code in {{301, 302, 303, 307, 308}}:
                location = exc.headers.get("location") or exc.headers.get("Location")
                if not location or redirect_count == 4:
                    raise RuntimeError("robots.txt exceeded the four-redirect safety limit") from exc
                next_url = urljoin(robots_url, str(location))
                parsed = urlsplit(next_url)
                if parsed.scheme not in {{"http", "https"}} or parsed.netloc != ALLOWED_NETLOC:
                    raise RuntimeError("robots.txt redirect left the allowed domain") from exc
                robots_url = next_url
                continue
            raise RuntimeError(f"robots.txt denied or unavailable (HTTP {{exc.code}})") from exc
        except urllib.error.URLError as exc:
            raise RuntimeError("robots.txt could not be read; refusing to scrape") from exc
    if lines is None:
        raise RuntimeError("robots.txt could not be evaluated; refusing to scrape")
    parser = Protego.parse("\\n".join(lines))
    if not parser.can_fetch(url, "WeaverBot"):
        raise RuntimeError(f"robots.txt disallows {{url}}")
    delay = parser.crawl_delay("WeaverBot") or parser.crawl_delay("*") or 0
    rate = parser.request_rate("WeaverBot") or parser.request_rate("*")
    if rate and rate.requests:
        delay = max(delay, rate.seconds / rate.requests)
    _ROBOTS_PARSER = parser
    _BROWSER_DELAY = max(1.0, float(delay))
    return _BROWSER_DELAY


def _robots_allows(url: str) -> bool:
    return ROBOTS_BYPASS or (
        _ROBOTS_PARSER is not None
        and _ROBOTS_PARSER.can_fetch(url, "WeaverBot")
    )


async def _public_browser_url(url: str) -> bool:
    parsed = urlsplit(url)
    if parsed.scheme not in {{"http", "https"}} or not parsed.hostname:
        return False
    try:
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
    except ValueError:
        return False
    if port not in {{80, 443}}:
        return False
    cached = _PUBLIC_HOST_CACHE.get(parsed.hostname)
    if cached is not None:
        return cached
    try:
        info = await asyncio.to_thread(socket.getaddrinfo, parsed.hostname, port, type=socket.SOCK_STREAM)
        addresses = set(entry[4][0] for entry in info)
        allowed = bool(addresses) and all(ipaddress.ip_address(address).is_global for address in addresses)
    except (OSError, ValueError):
        allowed = False
    _PUBLIC_HOST_CACHE[parsed.hostname] = allowed
    return allowed


async def _browser_page_setup(page: Any) -> None:
    async def guard(route: Any) -> None:
        request = route.request
        if request.url.startswith(("data:", "blob:", "about:")):
            await route.continue_()
            return
        if not await _public_browser_url(request.url):
            await route.abort()
            return
        if request.resource_type == "document":
            parsed = urlsplit(request.url)
            if (
                parsed.scheme not in {{"http", "https"}}
                or parsed.netloc != ALLOWED_NETLOC
                or not _robots_allows(request.url)
            ):
                await route.abort()
                return
            if request.url != SPEC["source_url"]:
                await asyncio.sleep(_BROWSER_DELAY)
        await route.continue_()

    await page.route("**/*", guard)


def _walk_jsonld(value: Any) -> Iterable[dict[str, Any]]:
    if isinstance(value, list):
        for item in value:
            yield from _walk_jsonld(item)
    elif isinstance(value, dict):
        if value.get("@type"):
            yield value
        for key in ("@graph", "itemListElement"):
            if key in value:
                yield from _walk_jsonld(value[key])


def _node_types(node: dict[str, Any]) -> set[str]:
    value = node.get("@type", [])
    values = value if isinstance(value, list) else [value]
    return {{str(item).lower() for item in values if item}}


def _path(value: Any, path: str) -> Any:
    current = value
    for part in path.split("."):
        if isinstance(current, list):
            current = current[0] if current else None
        if not isinstance(current, dict):
            return None
        current = current.get(part)
    if isinstance(current, dict):
        return current.get("value") or current.get("name") or current.get("url")
    return current


def _clean(value: Any, kind: str, base_url: str) -> Any:
    if isinstance(value, str):
        value = " ".join(value.split()).strip()
    if kind in {{"url", "image"}}:
        if isinstance(value, list):
            return [urljoin(base_url, str(item)) for item in value if item]
        return urljoin(base_url, str(value)) if value else None
    return value


def _canonical_url(url: str) -> str:
    parts = urlsplit(url)
    return urlunsplit((parts.scheme.lower(), parts.netloc.lower(), parts.path or "/", parts.query, ""))


def _detail_key(url: str) -> str:
    return _canonical_url(url).rstrip("/")


def _row_key(row: dict[str, Any]) -> str:
    for key in ("vin", "sku", "listing_id", "stock_number", "doi"):
        value = row.get(key)
        if value not in (None, "", []):
            return json.dumps([key, value], sort_keys=True, default=str, ensure_ascii=False)
    for key in ("apply_url", "url"):
        value = row.get(key)
        if value in (None, "", []):
            continue
        if isinstance(value, str):
            value = _canonical_url(value)
        primary = next((
            row.get(name)
            for name in ("title", "headline", "name", "quote", "item", "property", "instrument")
            if row.get(name) not in (None, "", [])
        ), None)
        return json.dumps([key, value, primary], sort_keys=True, default=str, ensure_ascii=False)
    return json.dumps(row, sort_keys=True, default=str, ensure_ascii=False, separators=(",", ":"))


def _next_page_url(response: Any) -> str | None:
    selectors = [selector for selector in (
        NEXT_SELECTOR,
        'link[rel~="next"]',
        'a[rel~="next"]',
        'a.next',
        '.next > a',
        '[aria-label*="next" i]',
        '[title*="next" i]',
        'a[href]',
    ) if selector]
    seen_nodes: set[tuple[str, str]] = set()
    ranked: list[tuple[int, int, str]] = []
    order = 0
    for selector in selectors:
        try:
            nodes = response.css(selector)
        except Exception:
            continue
        for node in nodes:
            href = str(node.attrib.get("href") or "").strip()
            marker = (href, str(node.get_all_text()))
            if not href or marker in seen_nodes or href.startswith(("#", "javascript:", "mailto:", "tel:")):
                continue
            seen_nodes.add(marker)
            next_url = urljoin(response.url, href)
            parsed = urlsplit(next_url)
            if parsed.scheme not in {{"http", "https"}} or parsed.netloc != ALLOWED_NETLOC:
                continue
            text = " ".join(str(node.get_all_text()).lower().split())
            attrs = " ".join(str(value) for value in node.attrib.values()).lower().replace("_", "-")
            rel = str(node.attrib.get("rel") or "").lower()
            score = 0
            if "next" in rel:
                score += 220
            if text in {{"next", "next page", "more", "more results", "older", "older posts", "›", "»", "→"}} or text.startswith(("next page", "next results")):
                score += 110
            if any(token in attrs for token in ("next", "pagination", "paginator", "pager")):
                score += 75
            if selector == NEXT_SELECTOR and selector != "a":
                score += 40
            page_match = re.search(r"(?:[?&](?:page|p|pg)=|/page/)(\\d+)", next_url, re.I)
            current_match = re.search(r"(?:[?&](?:page|p|pg)=|/page/)(\\d+)", response.url, re.I)
            current_page = int(current_match.group(1)) if current_match else 1
            if page_match and int(page_match.group(1)) == current_page + 1:
                score += 70
            if score >= 70:
                ranked.append((score, -order, next_url))
            order += 1
    return max(ranked, default=(0, 0, None), key=lambda item: (item[0], item[1]))[2]


def extract_rows(response: Any) -> Iterable[dict[str, Any]]:
    if SPEC["strategy"] == "jsonld":
        accepted_types = {{str(item).lower() for item in SPEC.get("jsonld_types", [])}}
        for raw in response.css("script[type='application/ld+json']::text").getall():
            try:
                payload = json.loads(raw)
            except (TypeError, json.JSONDecodeError):
                continue
            for node in _walk_jsonld(payload):
                if accepted_types and not accepted_types.intersection(_node_types(node)):
                    continue
                row = {{
                    field["name"]: _clean(_path(node, field["selector"]), field["type"], response.url)
                    for field in ACTIVE_FIELDS
                }}
                if any(value not in (None, "", []) for value in row.values()):
                    yield row
        return

    for record in response.css(SPEC["container"]):
        row = {{}}
        for field in ACTIVE_FIELDS:
            selector = field["selector"]
            attribute = field.get("attribute")
            nodes = [record] if selector == ":scope" else record.css(selector)
            if attribute:
                values = [node.attrib.get(attribute) for node in nodes]
                if attribute in {{"srcset", "data-srcset"}}:
                    values = [str(value).split(",")[0].strip().split(" ")[0] if value else value for value in values]
            else:
                values = [node.get_all_text() for node in nodes]
            values = [_clean(value, field["type"], response.url) for value in values]
            values = [value for value in values if value not in (None, "", [])]
            row[field["name"]] = values if field.get("multiple") else (values[0] if values else None)
        if any(value not in (None, "", []) for value in row.values()):
            yield row


def extract_detail_fields(response: Any) -> dict[str, Any]:
    row: dict[str, Any] = {{}}
    for field in ACTIVE_DETAIL_FIELDS:
        selector = field["selector"]
        attribute = field.get("attribute")
        try:
            nodes = response.css(selector)
        except Exception:
            nodes = []
        if attribute:
            values = [node.attrib.get(attribute) for node in nodes]
            if attribute in {{"srcset", "data-srcset"}}:
                values = [str(value).split(",")[0].strip().split(" ")[0] if value else value for value in values]
        else:
            values = [node.get_all_text() for node in nodes]
        values = [_clean(value, field["type"], response.url) for value in values]
        values = [value for value in values if value not in (None, "", [])]
        row[field["name"]] = values if field.get("multiple") else (values[0] if values else None)
    return row


def _detail_url_for(row: dict[str, Any]) -> str | None:
    if not DETAIL:
        return None
    value = row.get(DETAIL.get("url_field", "url"))
    if isinstance(value, list):
        value = next((item for item in value if isinstance(item, str)), None)
    if not isinstance(value, str):
        return None
    parsed = urlsplit(value)
    if parsed.scheme not in {{"http", "https"}} or parsed.netloc != ALLOWED_NETLOC:
        return None
    if DETAIL.get("append_trailing_slash") and not parsed.path.endswith("/"):
        value = urlunsplit((parsed.scheme, parsed.netloc, parsed.path + "/", parsed.query, ""))
    if (
        not ROBOTS_BYPASS
        and _ROBOTS_PARSER is not None
        and not _ROBOTS_PARSER.can_fetch(value, "WeaverBot")
    ):
        return None
    return value


class GeneratedSpider(Spider):
    name = "weaver_generated"
    start_urls = [SPEC["source_url"]]
    allowed_domains = {{{hostname!r}}}
    robots_txt_obey = not ROBOTS_BYPASS
    concurrent_requests = 1
    concurrent_requests_per_domain = 1
    download_delay = 1.0
    autothrottle_enabled = True

    def configure_sessions(self, manager: SessionManager) -> None:
        if SPEC.get("render_mode") == "browser":
            browser_options = {{
                "max_pages": 1,
                "headless": True,
                "network_idle": False,
                "timeout": 90_000,
                "solve_cloudflare": True,
                "page_setup": _browser_page_setup,
                "retries": 3,
                "wait": 1_500,
            }}
            if not ROBOTS_BYPASS:
                browser_options.update({{
                    "useragent": USER_AGENT,
                    "extra_headers": {{"User-Agent": USER_AGENT}},
                    "google_search": False,
                }})
            manager.add(
                "default",
                AsyncStealthySession(**browser_options),
            )
        else:
            manager.add(
                "default",
                FetcherSession(
                    follow_redirects=False,
                    headers={{"User-Agent": USER_AGENT}},
                    retries=0,
                ),
            )

    async def parse_detail(self, response: Response):
        source_row = response.meta.get("weaver_detail_row")
        row = dict(source_row) if isinstance(source_row, dict) else {{}}
        if response.status in {{301, 302, 303, 307, 308}}:
            location = response.headers.get("location") or response.headers.get("Location")
            redirect_count = int(response.meta.get("redirect_count", 0))
            if not location or redirect_count >= 5:
                print(f"[Weaver] detail redirect limit reached: {{response.url}}", flush=True)
                yield row
                return
            next_url = urljoin(response.url, str(location))
            next_parts = urlsplit(next_url)
            if (
                next_parts.scheme not in {{"http", "https"}}
                or next_parts.netloc != ALLOWED_NETLOC
                or not _robots_allows(next_url)
            ):
                print(f"[Weaver] detail redirect rejected: {{next_url}}", flush=True)
                yield row
                return
            await asyncio.sleep(_BROWSER_DELAY)
            meta = dict(response.meta or {{}})
            meta["redirect_count"] = redirect_count + 1
            yield Request(next_url, callback=self.parse_detail, meta=meta)
            return
        values = extract_detail_fields(response)
        for name, value in values.items():
            if row.get(name) in (None, "", []) and value not in (None, "", []):
                row[name] = value
        found = sum(value not in (None, "", []) for value in values.values())
        print(f"[Weaver] detail fetched: {{response.url}} · {{found}}/{{len(ACTIVE_DETAIL_FIELDS)}} fields", flush=True)
        yield row

    async def parse(self, response: Response):
        if response.status in {{301, 302, 303, 307, 308}}:
            location = response.headers.get("location") or response.headers.get("Location")
            redirect_count = int(response.meta.get("redirect_count", 0))
            if not location or redirect_count >= 5:
                raise RuntimeError("Target exceeded the five-redirect safety limit")
            next_url = urljoin(response.url, str(location))
            next_parts = urlsplit(next_url)
            if next_parts.scheme not in {{"http", "https"}} or next_parts.netloc != ALLOWED_NETLOC:
                raise RuntimeError("Redirect left the generated scraper's allowed domain")
            if not _robots_allows(next_url):
                raise RuntimeError("Redirect target is disallowed by robots.txt")
            await asyncio.sleep(_BROWSER_DELAY)
            yield Request(next_url, callback=self.parse, meta={{"redirect_count": redirect_count + 1}})
            return
        seen_urls = getattr(self, "_weaver_seen_urls", set())
        seen_rows = getattr(self, "_weaver_seen_rows", set())
        seen_pages = getattr(self, "_weaver_seen_pages", set())
        item_count = int(getattr(self, "_weaver_item_count", 0))
        page_count = int(getattr(self, "_weaver_page_count", 0))
        canonical = _canonical_url(response.url)
        if canonical in seen_urls:
            print(f"[Weaver] stop: page URL repeated: {{response.url}}", flush=True)
            return
        seen_urls.add(canonical)
        page_count += 1
        page_rows = list(extract_rows(response))
        page_key = json.dumps(sorted(_row_key(row) for row in page_rows), ensure_ascii=False)
        if page_key in seen_pages:
            print(f"[Weaver] stop: page {{page_count}} repeated an earlier dataset", flush=True)
            return
        seen_pages.add(page_key)
        print(f"[Weaver] page {{page_count}} fetched: {{response.url}}", flush=True)
        new_count = 0
        for row in page_rows:
            row_key = _row_key(row)
            if row_key in seen_rows:
                continue
            seen_rows.add(row_key)
            item_count += 1
            new_count += 1
            detail_url = _detail_url_for(row)
            if detail_url:
                print(f"[Weaver] detail queued: {{detail_url}}", flush=True)
                yield Request(
                    detail_url,
                    callback=self.parse_detail,
                    meta={{"redirect_count": 0, "weaver_detail_row": row}},
                )
            else:
                yield row
            if item_count >= MAX_ITEMS:
                break
        self._weaver_seen_urls = seen_urls
        self._weaver_seen_rows = seen_rows
        self._weaver_seen_pages = seen_pages
        self._weaver_item_count = item_count
        self._weaver_page_count = page_count
        print(f"[Weaver] page {{page_count}}: {{new_count}} new rows · {{item_count}} total", flush=True)
        if item_count >= MAX_ITEMS:
            if _next_page_url(response):
                print(f"[Weaver] stop: global row limit {{MAX_ITEMS}} reached", flush=True)
            else:
                print("[Weaver] stop: no next-page link found", flush=True)
            return
        if not new_count:
            print("[Weaver] stop: next page contained no new records", flush=True)
            return
        if page_count >= MAX_PAGES:
            print(f"[Weaver] stop: page safety cap {{MAX_PAGES}} reached", flush=True)
            return
        next_url = _next_page_url(response)
        if not next_url:
            print("[Weaver] stop: no next-page link found", flush=True)
            return
        if _canonical_url(next_url) in seen_urls:
            print(f"[Weaver] stop: next link cycles to {{next_url}}", flush=True)
            return
        if not _robots_allows(next_url):
            print(f"[Weaver] stop: robots.txt disallows next page {{next_url}}", flush=True)
            return
        print(f"[Weaver] next page inferred: {{next_url}}", flush=True)
        await asyncio.sleep(_BROWSER_DELAY)
        yield Request(next_url, callback=self.parse, meta={{"redirect_count": 0}})


def _fixture_rows(manifest: Any) -> list[dict[str, Any]]:
    if isinstance(manifest, dict):
        entries = manifest.get("pages", [])
        detail_entries = manifest.get("details", [])
    else:
        entries = manifest
        detail_entries = []
    detail_by_url = {{
        _detail_key(str(entry.get("url") or "")): entry
        for entry in detail_entries
        if entry.get("url") and entry.get("path")
    }}
    rows: list[dict[str, Any]] = []
    seen_rows: set[str] = set()
    seen_pages: set[str] = set()
    for page_number, entry in enumerate(entries[:MAX_PAGES], start=1):
        fixture = Path(entry["path"])
        page_url = entry.get("url") or SPEC["source_url"]
        page = Selector(fixture.read_bytes(), url=page_url)
        page_rows = list(extract_rows(page))
        page_key = json.dumps(sorted(_row_key(row) for row in page_rows), ensure_ascii=False)
        if page_key in seen_pages:
            print(f"[Weaver] fixture page {{page_number}} repeated an earlier dataset; stopping", flush=True)
            break
        seen_pages.add(page_key)
        new_count = 0
        for row in page_rows:
            key = _row_key(row)
            if key in seen_rows:
                continue
            seen_rows.add(key)
            detail_url = _detail_url_for(row)
            detail_entry = detail_by_url.get(_detail_key(detail_url)) if detail_url else None
            if detail_entry:
                detail_page = Selector(Path(detail_entry["path"]).read_bytes(), url=detail_entry["url"])
                values = extract_detail_fields(detail_page)
                for name, value in values.items():
                    if row.get(name) in (None, "", []) and value not in (None, "", []):
                        row[name] = value
            rows.append(row)
            new_count += 1
            if len(rows) >= MAX_ITEMS:
                break
        print(f"[Weaver] fixture page {{page_number}}: {{new_count}} new rows · {{len(rows)}} total · {{page_url}}", flush=True)
        if len(rows) >= MAX_ITEMS or not new_count:
            break
    return rows


def _validate_runtime_contract(rows: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    materialized = list(rows)
    if not materialized:
        raise RuntimeError("Selector contract failed: the scraper returned zero rows")
    if len(materialized) < MIN_ROWS:
        raise RuntimeError(
            f"Selector contract failed: expected at least {{MIN_ROWS}} records but received {{len(materialized)}}"
        )
    if PRIORITIZED_FIELDS and not any(
        row.get(name) not in (None, "", [])
        for row in materialized
        for name in PRIORITIZED_FIELDS
    ):
        raise RuntimeError(
            "Selector contract failed: none of the prioritized requested fields produced data"
        )
    for field in ACTIVE_FIELDS + ACTIVE_DETAIL_FIELDS:
        if not field.get("required"):
            continue
        name = field["name"]
        missing = sum(row.get(name) in (None, "", []) for row in materialized)
        if missing / len(materialized) > 0.20:
            raise RuntimeError(
                f"Selector contract failed: required field '{{name}}' was empty in {{missing}}/{{len(materialized)}} rows"
            )
    return materialized


def _report_failure(report_url: str, scraper_version: str, error: Exception) -> None:
    if not report_url:
        return
    parsed = urlsplit(report_url)
    if parsed.scheme not in {{"http", "https"}} or not parsed.netloc:
        print("[Weaver] failure report URL must be an absolute http(s) URL", file=sys.stderr, flush=True)
        return
    payload = json.dumps({{
        "error_type": type(error).__name__,
        "message": str(error)[:2_000] or "Generated scraper failed",
        "failed_url": SPEC["source_url"],
        "scraper_version": scraper_version,
        "selector": SPEC.get("container"),
        "robots_policy": ROBOTS_POLICY,
        "observed_at": datetime.now(timezone.utc).isoformat(),
        "auto_rebuild": True,
    }}).encode("utf-8")
    request = urllib.request.Request(
        report_url,
        data=payload,
        headers={{"Content-Type": "application/json", "Accept": "application/json", "User-Agent": USER_AGENT}},
        method="POST",
    )
    try:
        opener = urllib.request.build_opener(_NoRedirect)
        with opener.open(request, timeout=8) as response:
            response.read(64_000)
        print(f"[Weaver] runtime failure accepted by {{report_url}}", file=sys.stderr, flush=True)
    except Exception as report_error:
        print(
            f"[Weaver] runtime failure could not be reported ({{type(report_error).__name__}}); preserving the failed exit",
            file=sys.stderr,
            flush=True,
        )


def _run(args: argparse.Namespace) -> None:
    if args.fixture or args.fixture_manifest:
        if args.fixture_manifest:
            entries = json.loads(Path(args.fixture_manifest).read_text(encoding="utf-8"))
        else:
            entries = [{{"path": path, "url": SPEC["source_url"]}} for path in args.fixture]
        rows = _validate_runtime_contract(_fixture_rows(entries))
        Path(args.output).write_text(json.dumps(rows, indent=2, ensure_ascii=False), encoding="utf-8")
        fixture_count = (
            len(entries.get("pages", [])) + len(entries.get("details", []))
            if isinstance(entries, dict)
            else len(entries)
        )
        print(f"[Weaver] validated {{len(rows)}} unique rows from {{fixture_count}} fixture page(s)", flush=True)
        return
    GeneratedSpider.download_delay = preflight_robots(SPEC["source_url"])
    result = GeneratedSpider().start()
    _validate_runtime_contract(result.items)
    exporter = getattr(result.items, f"to_{{args.format}}")
    kwargs = {{"indent": 2}} if args.format == "json" else {{}}
    exporter(args.output, **kwargs)
    print(f"Wrote {{len(result.items)}} rows to {{args.output}}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Run this robots-aware Weaver scraper")
    parser.add_argument("--output", default="output.json")
    parser.add_argument("--format", choices=("json", "jsonl", "csv", "xml"), default="json")
    parser.add_argument("--fixture", action="append", help="Validate offline against one or more cached HTML fixtures")
    parser.add_argument("--fixture-manifest", help="JSON fixture list with path and page URL for full-crawl QA")
    parser.add_argument("--report-url", default=os.getenv("WEAVER_REPORT_URL", ""), help="POST sanitized runtime failures here")
    parser.add_argument("--scraper-version", default=os.getenv("WEAVER_SCRAPER_VERSION", "generated-v1"))
    args = parser.parse_args()
    try:
        _run(args)
    except Exception as error:
        _report_failure(args.report_url, args.scraper_version, error)
        raise


if __name__ == "__main__":
    main()
'''
